### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by ellipticcurv3** [ellipticcurv3/www#8]
In faux English also known as **Dark Mood**, it is possible to add dark mode by using media queries. Safari and Firefox handle it well. I tried using this on Windows (using a dark theme) with Firefox, and it works.

```css
@media (prefers-color-scheme: dark) {
  body { background-color: #101020; }
}
```

Time to work this out!
